import { z } from "zod";

/**
 * The wire contract. Every inbound socket payload is parsed through one of
 * these before a controller ever sees it — a client is untrusted input, and
 * until now the server read fields straight off the wire.
 *
 * Keep these in step with the client's emit() calls; they ARE the protocol.
 */

// Socket ids are opaque strings generated by Socket.IO (~20 url-safe chars).
const SocketId = z.string().min(1).max(64);

export const JoinSchema = z.object({
  roomId: z.string().trim().min(1).max(64),
  name: z.string().trim().min(1).max(30).catch("Guest"),
  media: z
    .object({
      audio: z.boolean().default(true),
      video: z.boolean().default(true),
    })
    .partial()
    .default({}),
});

// A partial patch: absent keys mean "unchanged", so every field is optional.
export const StateSchema = z
  .object({
    audio: z.boolean(),
    video: z.boolean(),
    sharing: z.boolean(),
    hand: z.boolean(),
  })
  .partial()
  .refine((v) => Object.keys(v).length > 0, { message: "empty state patch" });

export const ChatSchema = z.object({
  text: z.string().trim().min(1).max(2000),
});

export const ReactionSchema = z.object({
  // Constrained to the tray the UI actually offers — this is a broadcast
  // channel, so it must not become a way to push arbitrary strings at people.
  emoji: z.enum(["👍", "👏", "❤️", "😂", "🎉", "😮", "👋"]),
});

// --- WebRTC signaling ------------------------------------------------------
// SDP and ICE payloads are relayed verbatim to one peer, so we check the
// envelope (who it's for, roughly what shape) and let the browser parse the
// contents — re-implementing an SDP parser here would be its own bug farm.



// --- Host actions ----------------------------------------------------------

export const HostTargetSchema = z.object({ id: SocketId });
export const HostLockSchema = z.object({ locked: z.boolean() });
export const EmptySchema = z.any().optional();
